spring.application.name=sigeclin
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/sigeclin?sslmode=disable
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.thymeleaf.cache=false

logging.level.com.sigeclin=DEBUG
logging.level.org.springframework.security=TRACE

server.port=8080
spring.jpa.open-in-view=true
