-- MIGRACIÓN PARA NUEVOS CAMPOS DE DIRECCIONAMIENTO CLÍNICO
ALTER TABLE filiacion.paciente ADD COLUMN IF NOT EXISTS servicio_solicitado VARCHAR(100);
ALTER TABLE clinico.triaje ADD COLUMN IF NOT EXISTS servicio_destino VARCHAR(100);
